### ISSUE TITLE
Cancelling a swipe-away gesture for in-app safari views crashes the app

### ISSUE THREAD

**Issue by FlipABit** [insanj/Submarine-Issues#15]
This occurs on version 1.2.1 (2). Example video here: https://www.youtube.com/watch?v=2rnVUM8whW8. It does not appear to affect other view types.

**Comment by insanj** [comment]
Thanks for this! Appears to be related to SmartStickyPullToRefresh, unfortunately, and can be patched with a simple flag to force `stopDetectingPullToRefresh` to only remove observers _once_. When dismissing SafariViewController, for some reason, the `viewWillDisappear` method is called twice. In addition, after dismissing the base navigation controller appears to malfunction and have the same "stuck" glitch as the pre iOS 9.2 days. Rats! I can only fix the crash, not the latter issue.
